/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package imagem;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Tauan
 */
public class Window extends javax.swing.JFrame implements ActionListener {
    public void actionPerformed(ActionEvent e){
        if(e.getSource()==sair){
            System.exit(0);
        }
    }
    public Window() {
        //title
        super("Combate"); 
        initComponents();        
   //size Tela
        setSize(640,480);
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);  
        Center();
        Inicio();
        Creditos();
        Sair();
        Regras();
        initComponents();
        try{
            Image icon = Toolkit.getDefaultToolkit().getImage("src/Imagens/Capacete.jpg");
            setIconImage(icon);
            imagem_fundo();
                       
        } catch (Exception e){
            JOptionPane.showInternalMessageDialog(null, e, "Erro!", 0);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.highlight"));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void imagem_fundo(){
    try{
         setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         jLabel1.setIcon(new ImageIcon("src/Imagens/Tela.jpg"));
         add(jLabel1);
         pack();
         this.setSize(640,480);
    }catch (Exception e){
        JOptionPane.showMessageDialog(rootPane, e, "erro!", 0);
    }
}

public void Center(){
    Toolkit tk = Toolkit.getDefaultToolkit();
    Dimension screenSize = tk.getScreenSize();
    
    int screenWidth = screenSize.width - this.getWidth();
    int screenHeight = screenSize.height - this.getHeight();
    
    setLocation(screenWidth/2, screenHeight/2);
    }

    public void Inicio(){
        JButton inicio=new JButton("Início");  
        setLayout(null);
        inicio.setBounds(245,50,150,50);
        add(inicio);
        inicio.setBackground(new Color(38,109,7));
        inicio.setForeground(Color.white);
    }
    public void Creditos(){
        JButton creditos=new JButton("Créditos");  
        setLayout(null);
        creditos.setBounds(245,150,150,50);
        add(creditos);
        creditos.setBackground(new Color(38,109,7));
        creditos.setForeground(Color.white);
    }
    JButton sair=new JButton("Sair"); 
    public void Sair(){
         
        setLayout(null);
        sair.setBounds(245,350,150,50);
        add(sair);
        sair.addActionListener(this);
        sair.setBackground(new Color(38,109,7));
        sair.setForeground(Color.white);
    }
    
    public void Regras(){
        JButton regras=new JButton("Regras");  
        setLayout(null);
        regras.setBounds(245,250,150,50);
        add(regras);
        regras.setBackground(new Color(38,109,7));
        regras.setForeground(Color.white);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
          public void run() {
               new Window().setVisible(true);
           }
       });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

